### ISSUE TITLE
BotBuilderCommunity suggestion

### ISSUE THREAD

**Issue by EricDahlvang** [botbuilder-contrib/botbuilder-storage-mongodb#10]
It would be great if you could move this to the community repository: https://github.com/BotBuilderCommunity/botbuilder-community-js

**Comment by nurih** [comment]
Interesting suggestion.
Though that repo serves similar purpose, it is owned, maintained, and structured very differently.
For example, the folder structure there is conducive to creating a single NPM package for all storage adapters. Our current view is that each component should stand alone. This granular approach promotes smaller install footprint and no un-necessary dependencies. For example: why would a Redis storage adapter need to install a MongoDB or an Azure Tables adapter?

**Comment by EricDahlvang** [comment]
Interesting.  The dotnet community repository does have everything separated into different libraries: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop/libraries

I have no idea why the js one is not the same way, but it definitely should be.

**Comment by EricDahlvang** [comment]
@nurih It sounds like they are open to a a botbuilder-storage-mongodb folder under the libraries folder, and released as a standalone package: https://github.com/BotBuilderCommunity/botbuilder-community-js/issues/50

Regardless, thanks for your work on this.  Great contribution!
