### ISSUE TITLE
Unable to pass option { useUnifiedTopology: true } to the MongoClient constructor

### ISSUE THREAD

**Issue by bahyali** [botbuilder-contrib/botbuilder-storage-mongodb#13]
My console keeps giving me this warning, I checked and I can't seem to configure the connection to pass the option.

> DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, **pass option { useUnifiedTopology: true }** to the MongoClient constructor.

https://github.com/botbuilder-contrib/botbuilder-storage-mongodb/blob/8c36d4380252c304c504cc01c9294d826a300fbe/src/MongoDbStorage.ts#L55

I hope you fix it before deprecation.

_Mongo Version: MongoDB 4.2.2_

**Comment by laeckerv** [comment]
Fixed with https://github.com/botbuilder-contrib/botbuilder-storage-mongodb/pull/17/commits/89287de63ae5303eaa3d4fe9e5a64184074c31bd

**Comment by mrpinkcat** [comment]
I still have the issue :/

**Comment by laeckerv** [comment]
I believe it isn't published yet.

**Comment by mrpinkcat** [comment]
You mean publish on npm ? Sorry, I don't know how it works.

**Comment by bahyali** [comment]
Thank you, this should do it!
